env:
    browser: true
    es6: true
    node: true
extends:
    - 'eslint:recommended'
    - 'plugin:vue/essential'
parserOptions:
    sourceType: 'module'
    ecmaVersion: 2018
rules:
    indent:
        - error
        - 4
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - single
    semi:
        - error
        - always
    no-console:
        - error
        - allow:
            - warn
            - error
    no-unused-vars:
        - error
        - args: none
globals:
    logger: false
    _: false
